### ISSUE TITLE
Error with submission of valid deadline

### ISSUE THREAD

**Issue by Kafkamorph** [JohnnyFFM/miner-burst#4]
> 19:44:47 [ xxx] found DL:        1321996
> 19:44:47 [ xxx] sent DL:         1321996    15d 07:13:16
> 19:44:50 [ xxx] confirmed DL:    1321996    15d 07:13:16
> 19:44:51 [ xxx] found DL:         264627
> 19:44:51 [ xxx] sent DL:          264627     3d 01:30:27
> [ERROR 942682161] deadline exceeds deadline limit of the pool
>

**Comment by JohnnyFFM** [comment]
->this is a plot file issue. Poc1 or 2? Every deadline or just some deadlines?

**Comment by Kafkamorph** [comment]
Right now, a mix.
I'm using your Plot Converter v2.3.
Is there any way to verify all plots' integrity?... 

Edit - the odd thing is, if I use Creepminer I got no errors and pool accepts submissions.
I just tried both miners (same plots, same pool) on same block to test.

**Comment by JohnnyFFM** [comment]
Difficult to compare, because creepminer and blagominer dont scan the files in the same order. The faulty deadline might be ignored on creepminer because a better deadline has already been found. A complete verification of a plot file is difficult, same computational  effort as replotting. 

I suggest to take the following two steps:
1.) Please check your miner.conf if POC2StartBlock is set top 502000
2.) To track down borked plot files I recommend : 
https://github.com/guneyozsan/burst-corrupted-plot-detector

It analyses your log files and compares submitted deadlines vs confirmed deadlines per file. If you spot a file with a high amount of unconfirmed deadlines, the file is borked and should be replottet.

**Comment by Kafkamorph** [comment]
Will do.

Cheers!
